import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import PaymentForm from '@/components/PaymentForm';

export default function Home() {
  const paymentHandler = (tokenId: string, cardId: string) => {
    console.log('Token ID: ', tokenId);
    console.log('Card ID: ', cardId);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <PaymentForm paymentHandler={paymentHandler} buttonName="Pay">
            <div>Payment details will go here</div>
          </PaymentForm>
        </div>
      </main>
    </>
  );
}
